version: '3.9'
services:
  python:
    restart: always
    image: ichiharanaruki/scientifictoolset:base
    container_name: 'optimizationtools'
    working_dir: '/root/'
    tty: true
    volumes:
    - ../:/workdir
